### ISSUE TITLE
Add Scroll Support

### ISSUE THREAD

**Issue by nuconomy** [0xCazador/defi-simulator#20]
Thanks for creating such a useful tool. As Aave now supports the Scroll L2, it would be good to be able to access that data in the simulator.

**Comment by 0xCazador** [comment]
Thanks for the issue. I agree, it’d be good to get Scroll added ASAP. I’ll take a look at potential providers and hopefully get it added soon.

**Comment by 0xCazador** [comment]
Support for the Scroll market, along with Gnosis and BNB, are now live. Here's an example Scroll position for reference: https://defisim.xyz/?address=0x9824697f7c12cabada9b57842060931c48dea969

Thanks again for raising this issue!
